### ISSUE TITLE
为何yolo效果比较差

### ISSUE THREAD

**Issue by xilinniao123** [ccjaread/tianchi_tile_defect_detection#1]
感谢分享，请问楼主有没有分析为何yolo效果会比较差

**Comment by ccjaread** [comment]
我也是新手啦，只能说yolov5的s版特征提取不足吧，显存够可以上l或x的，另外发现mAP越高混淆矩阵中类别误判越多，可能和选择的loss的反向传播不均衡有关，此外瞎猜focus层的分解是不是对小目标检测有影响
